version: "3.8"
services:
  web:
    build: .
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "nom_de_la_base_de_donnees"
      MYSQL_USER: "utilisateur"
      MYSQL_PASSWORD: "mot_de_passe"
      MYSQL_ROOT_PASSWORD: "mot_de_passe_root"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/ssl/certs:ro
    depends_on:
      - web
volumes:
  db_data:
