version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: flask run

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend/static:/usr/share/nginx/html/static
      - ./frontend/templates:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/ssl/certs:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "nom_de_la_base_de_donnees"
      MYSQL_USER: "utilisateur"
      MYSQL_PASSWORD: "mot_de_passe"
      MYSQL_ROOT_PASSWORD: "mot_de_passe_root"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
