version: "3.8" # Specify the version of the Docker Compose file format

services:
  # Define the 'web' service that builds the Flask application
  web:
    build: . # Build the Docker image using the Dockerfile in the current directory
    depends_on:
      - db # Specify dependency on the 'db' service, ensuring it starts first

  # Define the 'db' service that runs MySQL
  db:
    image: mysql:5.7 # Use the MySQL version 5.7 Docker image
    environment:
      MYSQL_DATABASE: "nom_de_la_base_de_donnees" # Set the MySQL database name
      MYSQL_USER: "utilisateur" # Set the MySQL user
      MYSQL_PASSWORD: "mot_de_passe" # Set the MySQL password
      MYSQL_ROOT_PASSWORD: "mot_de_passe_root" # Set the MySQL root password
    ports:
      - "3306:3306" # Map port 3306 inside the container to port 3306 on the host
    volumes:
      - db_data:/var/lib/mysql # Persist database data using a named volume

  # Define the 'nginx' service that runs NGINX
  nginx:
    image: nginx:latest # Use the latest NGINX Docker image
    ports:
      - "80:80" # Map HTTP port 80 on the host to port 80 in the container
      - "443:443" # Map HTTPS port 443 on the host to port 443 in the container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # Mount the NGINX config file as read-only
      - ./certs:/etc/ssl/certs:ro # Mount the SSL certificates directory as read-only
    depends_on:
      - web # Specify dependency on the 'web' service

# Define named volumes that can be used by services
volumes:
  db_data: # Declare a named volume for MySQL data to ensure data persists
